<?php

namespace skill961
{
	$skill961_npc = array
	(
		'mode' => 1,
		'num' => 1,
		'pass' => 'bra',
		'club' => 17,
		'bid' => 0,
		'inf' => '',
		'rage' => 0,
		'pose'=> 5,
		'tactic' => 3,
		'killnum' => 0,
		'teamID' => '',
		'teamPass' => '',
		'gd' => 'f',
		'pls' => 0,
		'mhp' => 1666,
		'msp' => 8888,
		'att' => 233,
		'def' => 233,
		'lvl' => 9,
		'skill' => 233,
		'skills' => array('513'=>'0'),
		'money' => 233,
		'arb' => '毛绒外套',
		'arbk' => 'DB',
		'arbe' => 240,
		'arbs' => 200,
		'arbsk' => '',
		'arh' => '眼罩',
		'arhk' => 'DH',
		'arhe' => 120,
		'arhs' => 200,
		'arhsk' => '',
		'ara' => '抱枕',
		'arak' => 'DA',
		'arae' => 120,
		'aras' => 200,
		'arask' => 'H',
		'arf' => '尾巴？',
		'arfk' => 'DF',
		'arfe' => 120,
		'arfs' => 200,
		'arfsk' => '',
		'art' => '幻境通行证',
		'artk' => 'A',
		'arte' => 1,
		'arts' => 1,
		'artsk' => 'c',
		'sub' => array
		(
			0 => array
			(
				'name' => '『Hyper』',
				'icon' => 'f_0.gif',
				'wep' => '「守家巨炮-节能模式」',
				'wepk' => 'WF',
				'wepe' => 233,
				'weps' => 999,
				'wepsk' => 'Y',
				'itm1' => '薯片',
				'itmk1' => 'HB',
				'itme1' => 233,
				'itms1' => 30,
				'itmsk1' => '',
			),
		),
	);
}
?>