input,core/input/,1
bubblebox,extra/misc/bubblebox/,1
glowbutton,extra/misc/glowbutton/,1
sys,core/sys/,1
map,core/map/,1
bmp_util,extra/misc/bmp_util/,1
gameflow_base,core/gameflow/gameflow_base/,1
player,core/player/,1
gameflow_antiafk,core/gameflow/gameflow_antiafk/,1
logger,base/logger/,1
skillbase,base/skillbase/,1
replay,extra/misc/replay/,1
elorating,extra/misc/elorating/,1
achievement_base,extra/achievement/achievement_base/,1
bufficons,extra/misc/bufficons/,1
explore,base/explore/,1
noise,base/noise/,1
lvlctl,base/lvlctl/,1
skill11,extra/club/skills/skill11/,1
skill10,extra/club/skills/skill10/,1
itemmain,base/itemmain/,1
skill4,base/skills/skill4/,1
npc,base/npc/,1
skill13,extra/club/skills/skill13/,1
skill14,extra/club/skills/skill14/,1
skill15,extra/club/skills/skill15/,1
skill16,extra/club/skills/skill16/,1
skill17,extra/club/skills/skill17/,1
skill18,extra/club/skills/skill18/,1
skill24,extra/club/skills/skill24/,1
metman,base/metman/,1
itemmix,base/itemmix/itemmix/,1
itemshop,base/itemshop/,1
edible,base/items/edible/,1
radar,base/items/radar/,1
armor_art,base/armor_art/,1
boxes,base/items/boxes/,1
scpdrink,base/items/scpdrink/,1
item_ub,base/items/item_ub/,1
item_uee,base/items/item_uee/,1
song,base/items/song/,1
skill23,extra/club/skills/skill23/,1
corpse,base/corpse/,1
trap,base/items/trap/,1
itemmix_sync,base/itemmix/itemmix_sync/,1
itemmix_overlay,base/itemmix/itemmix_overlay/,1
skill20,extra/club/skills/skill20/,1
skill69,extra/club/skills/skill69/,1
skill300,extra/achievement/skills/skill300/,1
attrbase,extra/attr/attrbase/,1
cooldown,base/cooldown/,1
enemy,base/enemy/,1
gameflow_duel,core/gameflow/gameflow_duel/,1
ex_attr_trap,extra/attr/ex_attr_trap/,1
skill19,extra/club/skills/skill19/,1
skill22,extra/club/skills/skill22/,1
autopower,extra/misc/autopower/,1
team,base/team/,1
battle,base/battle/,1
item_misc,base/items/item_misc/,1
gameflow_combo,core/gameflow/gameflow_combo/,1
advteam,extra/misc/advteam/,1
attack,base/attack/,1
clubbase,extra/club/clubbase/,1
weapon,base/weapon/weapon/,1
npcchat,base/npcchat/,1
skill21,extra/club/skills/skill21/,1
ex_hp_def,extra/attr/ex_hp_def/,1
skill204,extra/club/skills/skill204/,1
skill39,extra/club/skills/skill39/,1
skill29,extra/club/skills/skill29/,1
skill31,extra/club/skills/skill31/,1
skill40,extra/club/skills/skill40/,1
club1,extra/club/clubs/club1/,1
club2,extra/club/clubs/club2/,1
club3,extra/club/clubs/club3/,1
club4,extra/club/clubs/club4/,1
club5,extra/club/clubs/club5/,1
club9,extra/club/clubs/club9/,1
club99,extra/club/clubs/club99/,1
club17,extra/club/clubs/club17/,1
club20,extra/club/clubs/club20/,1
club13,extra/club/clubs/club13/,1
club14,extra/club/clubs/club14/,1
sklearn_util,extra/club/sklearn_util/,1
club6,extra/club/clubs/club6/,1
club11,extra/club/clubs/club11/,1
skill58,extra/club/skills/skill58/,1
club24,extra/club/clubs/club24/,1
skill67,extra/club/skills/skill67/,1
skill68,extra/club/skills/skill68/,1
club18,extra/club/clubs/club18/,1
skill211,extra/club/skills/skill211/,1
skill212,extra/club/skills/skill212/,1
skill214,extra/club/skills/skill214/,1
wep_n,base/weapon/wep_n/,1
wep_p,base/weapon/wep_p/,1
wep_k,base/weapon/wep_k/,1
wep_c,base/weapon/wep_c/,1
wep_d,base/weapon/wep_d/,1
wep_f,base/weapon/wep_f/,1
item_um,base/items/item_um/,1
tactic,base/tactic/,1
mapattr,base/mapattr/,1
wound,base/wound/,1
skill2,base/skills/skill2/,1
skill3,base/skills/skill3/,1
ex_phy_def,extra/attr/ex_phy_def/,1
item_uv,base/items/item_uv/,1
rage,extra/attr/rage/,1
skill30,extra/club/skills/skill30/,1
skill35,extra/club/skills/skill35/,1
skill41,extra/club/skills/skill41/,1
skill45,extra/club/skills/skill45/,1
skill46,extra/club/skills/skill46/,1
skill52,extra/club/skills/skill52/,1
skill60,extra/club/skills/skill60/,1
skill61,extra/club/skills/skill61/,1
skill62,extra/club/skills/skill62/,1
skill63,extra/club/skills/skill63/,1
skill64,extra/club/skills/skill64/,1
skill203,extra/club/skills/skill203/,1
skill209,extra/club/skills/skill209/,1
skill66,extra/club/skills/skill66/,1
skill70,extra/club/skills/skill70/,1
skill71,extra/club/skills/skill71/,1
skill74,extra/club/skills/skill74/,1
skill213,extra/club/skills/skill213/,1
skill216,extra/club/skills/skill216/,1
skill404,extra/club/skills/skill404/,1
skill403,extra/club/skills/skill403/,1
skill400,extra/club/skills/skill400/,1
skill402,extra/club/skills/skill402/,1
skill401,extra/club/skills/skill401/,1
skill53,extra/club/skills/skill53/,1
skill55,extra/club/skills/skill55/,1
skill72,extra/club/skills/skill72/,1
skill59,extra/club/skills/skill59/,1
wep_g,base/weapon/wep_g/,1
wep_j,base/weapon/wep_j/,1
miracletrap,base/items/miracletrap/,1
event,base/event/,1
skill5,extra/attr/skills/skill5/,1
skill6,extra/attr/skills/skill6/,1
skill7,extra/attr/skills/skill7/,1
skill8,extra/attr/skills/skill8/,1
skill9,extra/attr/skills/skill9/,1
poison,base/items/poison/,1
armor,base/armor/,1
rest,base/rest/,1
ex_rapid_attr,extra/attr/ex_rapid_attr/,1
item_uc,base/items/item_uc/,1
skill12,extra/club/skills/skill12/,1
skill28,extra/club/skills/skill28/,1
skill37,extra/club/skills/skill37/,1
skill73,extra/club/skills/skill73/,1
skill36,extra/club/skills/skill36/,1
skill38,extra/club/skills/skill38/,1
dualwep,base/weapon/dualwep/,1
ammunition,base/items/ammunition/,1
ex_attr_silencer,extra/attr/ex_attr_silencer/,1
ex_dmg_att,extra/attr/ex_dmg_att/,1
ex_attr_charge,extra/attr/ex_attr_charge/,1
empowers,base/items/empowers/,1
skill32,extra/club/skills/skill32/,1
skill202,extra/club/skills/skill202/,1
pose,base/pose/,1
skill1,base/skills/skill1/,1
skill207,extra/club/skills/skill207/,1
skill65,extra/club/skills/skill65/,1
skill49,extra/club/skills/skill49/,1
skill201,extra/club/skills/skill201/,1
ex_dmg_def,extra/attr/ex_dmg_def/,1
ex_dmg_nullify,extra/attr/ex_dmg_nullify/,1
skill25,extra/club/skills/skill25/,1
skill44,extra/club/skills/skill44/,1
skill47,extra/club/skills/skill47/,1
skill48,extra/club/skills/skill48/,1
skill54,extra/club/skills/skill54/,1
skill205,extra/club/skills/skill205/,1
skill75,extra/club/skills/skill75/,1
skill76,extra/club/skills/skill76/,1
skill210,extra/club/skills/skill210/,1
ex_phy_nullify,extra/attr/ex_phy_nullify/,1
wepchange,extra/attr/wepchange/,1
blessstone,extra/attr/blessstone/,1
skill33,extra/club/skills/skill33/,1
weather,base/weather/,1
npcinfo,extra/misc/npcinfo/,1
skill206,extra/club/skills/skill206/,1
skill34,extra/club/skills/skill34/,1
skill208,extra/club/skills/skill208/,1
skill215,extra/club/skills/skill215/,1
skill26,extra/club/skills/skill26/,1
skill51,extra/club/skills/skill51/,1
ex_gender_attr,extra/attr/ex_gender_attr/,1
ex_attr_pierce,extra/attr/ex_attr_pierce/,1
skill42,extra/club/skills/skill42/,1
addnpc,base/addnpc/,1
skill50,extra/club/skills/skill50/,1
skill27,extra/club/skills/skill27/,1
skill43,extra/club/skills/skill43/,1
skill56,extra/club/skills/skill56/,1
skill57,extra/club/skills/skill57/,1
