<?php

namespace addnpc
{
	$npcinit = array
		(
			'name' => '',	'pass' => 'bra', 'gd' => 'm',	'icon' => 0,	'club' => 0,	
			'mhp' => 0,	'msp' => 0,	'att' => 0,	'def' => 0,	'pls' => 0,	'lvl' => 0,
			'money' => 0,	'inf' => '',	'rage' => 0,	'pose' => 0,	'tactic' => 0,	
			'killnum' => 0,	'state' => 1,	'teamID' => '',	'teamPass' => '','bid' => 0,
			'wep' => '',	'wepk' => '',	'wepe' => 0,	'weps' => 0,	'wepsk' => '',
			'arb' => '',	'arbk' => '',	'arbe' => 0,	'arbs' => 0,	'arbsk' => '',
			'arh' => '',	'arhk' => '',	'arhe' => 0,	'arhs' => 0,	'arhsk' => '',
			'arf' => '',	'arfk' => '',	'arfe' => 0,	'arfs' => 0,	'arfsk' => '',
			'ara' => '',	'arak' => '',	'arae' => 0,	'aras' => 0,	'arask' => '',
			'art' => '',	'artk' => '',	'arte' => 0,	'arts' => 0,	'artsk' => '',
			'itm0' => '',	'itmk0' => '',	'itme0' => 0,	'itms0' => 0,	'itmsk0' => '',
			'itm1' => '',	'itmk1' => '',	'itme1' => 0,	'itms1' => 0,	'itmsk1' => '',
			'itm2' => '',	'itmk2' => '',	'itme2' => 0,	'itms2' => 0,	'itmsk2' => '',
			'itm3' => '',	'itmk3' => '',	'itme3' => 0,	'itms3' => 0,	'itmsk3' => '',
			'itm4' => '',	'itmk4' => '',	'itme4' => 0,	'itms4' => 0,	'itmsk4' => '',
			'itm5' => '',	'itmk5' => '',	'itme5' => 0,	'itms5' => 0,	'itmsk5' => '',
			'itm6' => '',	'itmk6' => '',	'itme6' => 0,	'itms6' => 0,	'itmsk6' => '',
		);
	$anpcinfo = array
		( 
		4 => array
			(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 9,
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 10,
			'pose'=> 4,
			'tactic' => 4,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'f',
			'pls' => 33,
			'mhp' => 300,
			'msp' => 400,
			'att' => 800000,
			'def' => 800000,
			'lvl' => 250,
			'skill' => 50000,
			'money' => 1,
			'arb' => '黑色连衣裙',
			'arbk' => 'DB',
			'arbe' => 800,
			'arbs' => 20,
			'arbsk' => 'Aa',
			'arh' => '红色的丝带',
			'arhk' => 'DH',
			'arhe' => 800,
			'arhs' => 15,
			'arhsk' => 'B',
			'arf' => '黑色布鞋',
			'arfk' => 'DF',
			'arfe' => 800,
			'arfs' => 21,
			'ara' => '红色的丝带',
			'arak' => 'DA',
			'arae' => 800,
			'aras' => 15,
			'arask' => 'b',
			'art' => '十字发卡',
			'artk' => 'Y',
			'arte' => 1,
			'arts' => 1,
			'sub' => array
			(
				0 => array
				(
				'name' => '■',
				'icon' => 83,
				'wep' => '红色的丝带',
				'wepk' => 'WP',
				'wepe' => 800,
				'weps' => 20,
				'wepsk' => 'u',
				),
			),
		),
		7 => array
			(
			'mode' => 1,
			'num' => 3,
			'pass' => 'bra',
			'club' => 9,
			'bid' => 0,
			'inf' => '',
			'rage' => 100,
			'pose'=> 1,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'pls' => 99,
			'mhp' => 2550,
			'msp' => 400,
			'att' => 250,
			'def' => 750,
			'lvl' => 60,
			'skill' => 500,
			'money' => 24000,
			'arb' => '【执行官装甲-改】',
			'arbk' => 'DB',
			'arbe' => 700,
			'arbs' => 120,
			'arbsk' => 'Aa',
			'arh' => '【执行官头盔-改】',
			'arhk' => 'DH',
			'arhe' => 500,
			'arhs' => 120,
			'arhsk' => '',
			'arf' => '【执行官战靴-改】',
			'arfk' => 'DF',
			'arfe' => 480,
			'arfs' => 120,
			'arfsk' => '',
			'ara' => '【执行官护手-改】',
			'arak' => 'DA',
			'arae' => 480,
			'aras' => 120,
			'arask' => 'c',
			'art' => '【HP制御系统】',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'H',
	//		'itm5' => '好人卡',
	//		'itmk5' => 'Y',
	//		'itme5' => 1,
	//		'itms5' => 240,
			'sub' => array
			(
				0 => array
				(
				'name' => '电击使 御坂 美琴',
				'icon' => 41,
				'gd' => 'f',
				'wep' => '【科学的超电磁炮-改】',
				'wepk' => 'WG',
				'wepe' => 770,
				'weps' => 999,
				'wepsk' => 'ed',
				'itm1' => '社员专用的ID卡',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				),
				1 => array
				(
				'name' => '班主任 坂持 金发',
				'icon' => 42,
				'gd' => 'm',
				'wep' => '【水素粒子水铁炮-改】',
				'wepk' => 'WG',
				'wepe' => 770,
				'weps' => 999,
				'wepsk' => 'id',
				'itm1' => '社员专用的ID卡',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				),
				2 => array
				(
				'name' => '花之领主 风见 幽香',
				'icon' => 43,
				'gd' => 'f',
				'wep' => '魔炮【元祖二重魔炮】',
				'wepk' => 'WF',
				'wepe' => 770,
				'weps' => 999,
				'wepsk' => 'pd',
				'itm1' => '社员专用的ID卡',
				'itmk1' => 'Z',
				'itme1' => 1,
				'itms1' => 1,
				),
			),
		),
		
		12 => array
			(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 99,
			'bid' => 0,
			'inf' => '',
			'skills' => array('401'=>'5'),
			'state' => 1,
			'rage' => 10,
			'pose'=> 4,
			'tactic' => 4,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'f',
			'pls' => 99,
			'mhp' => 1800,
			'msp' => 400,
			'att' => 150,
			'def' => 260,
			'lvl' => 18,
			'skill' => 30,
			'money' => 1,
			'arb' => '黑色哥特装',
			'arbk' => 'DB',
			'arbe' => 25,
			'arbs' => 20,
			'arh' => '不明饰物',
			'arhk' => 'DH',
			'arhe' => 12,
			'arhs' => 15,
			'arf' => '黑色布鞋',
			'arfk' => 'DF',
			'arfe' => 18,
			'arfs' => 21,
			'ara' => '黑铁镣铐',
			'arak' => 'DA',
			'arae' => 5,
			'aras' => 15,
			'art' => '镣铐的碎片',
			'artk' => 'Y',
			'arte' => 1,
			'arts' => 1,
			'sub' => array
			(
				0 => array
				(
				'name' => 'Dark Force幼体',
				'icon' => 81,
				'wep' => 'RV『Black Riper』',
				'wepk' => 'WG',
				'wepe' => 80,
				'weps' => 125,
				'wepsk' => 'c',
				),
			),
		),
		
		13 => array(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 99,
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 5,
			'pose'=> 0,
			'tactic' => 0,
			'killnum' => 0,
			'teamID' => '循环',
			'teampsss' => 'circle',
			'gd' => 'f',
			'pls' => 99,
			'mhp' => 600,
			'msp' => 400,
			'att' => 150,
			'def' => 100,
			'lvl' => 10,
			'skill' => 50,
			'money' => 500,
			'arb' => '旧式布拉吉',
			'arbk' => 'DB',
			'arbe' => 75,
			'arbs' => 20,
			'arbsk' => '',
			'arh' => '蝙蝠羽翼帽子',
			'arhk' => 'DH',
			'arhe' => 75,
			'arhs' => 20,
			'arf' => '女式皮鞋',
			'arfk' => 'DF',
			'arfe' => 75,
			'arfs' => 20,
			'ara' => '粉色披风',
			'arak' => 'DA',
			'arae' => 50,
			'aras' => 25,
			'art' => '飞行之愿',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'H',
			'sub' => array
			(
				0 => array
				(
				'name' => '库特',
				'icon' => 8,
				'wep' => '光束镰刀',
				'wepk' => 'WK',
				'wepe' => 100,
				'weps' => 36,
				'wepsk' => 'ec',
				),
			),
		), 
	);
}

?>