<?php

namespace addnpc
{
	$npcinit = array
	(
		'name' => '',	'pass' => 'bra', 'gd' => 'm',	'icon' => 0,	'club' => 0,	
		'mhp' => 0,	'msp' => 0,	'att' => 0,	'def' => 0,	'pls' => 0,	'lvl' => 0,
		'money' => 0,	'inf' => '',	'rage' => 0,	'pose' => 0,	'tactic' => 0,	
		'killnum' => 0,	'npckillnum' => 0, 'state' => 1,	'teamID' => '',	'teamPass' => '','bid' => 0,
		'wep' => '',	'wepk' => '',	'wepe' => 0,	'weps' => 0,	'wepsk' => '',
		'arb' => '',	'arbk' => '',	'arbe' => 0,	'arbs' => 0,	'arbsk' => '',
		'arh' => '',	'arhk' => '',	'arhe' => 0,	'arhs' => 0,	'arhsk' => '',
		'arf' => '',	'arfk' => '',	'arfe' => 0,	'arfs' => 0,	'arfsk' => '',
		'ara' => '',	'arak' => '',	'arae' => 0,	'aras' => 0,	'arask' => '',
		'art' => '',	'artk' => '',	'arte' => 0,	'arts' => 0,	'artsk' => '',
		'itm0' => '',	'itmk0' => '',	'itme0' => 0,	'itms0' => 0,	'itmsk0' => '',
		'itm1' => '',	'itmk1' => '',	'itme1' => 0,	'itms1' => 0,	'itmsk1' => '',
		'itm2' => '',	'itmk2' => '',	'itme2' => 0,	'itms2' => 0,	'itmsk2' => '',
		'itm3' => '',	'itmk3' => '',	'itme3' => 0,	'itms3' => 0,	'itmsk3' => '',
		'itm4' => '',	'itmk4' => '',	'itme4' => 0,	'itms4' => 0,	'itmsk4' => '',
		'itm5' => '',	'itmk5' => '',	'itme5' => 0,	'itms5' => 0,	'itmsk5' => '',
		'itm6' => '',	'itmk6' => '',	'itme6' => 0,	'itms6' => 0,	'itmsk6' => '',
	);
	
	$anpcinfo = array
	( 
		4 => array
		(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 9,
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 10,
			'pose'=> 4,
			'tactic' => 4,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'f',
			'pls' => 33,
			'mhp' => 300,
			'msp' => 400,
			'att' => 800000,
			'def' => 800000,
			'lvl' => 250,
			'skill' => 50000,
			'money' => 1,
			'arb' => '黑色连衣裙',
			'arbk' => 'DB',
			'arbe' => 800,
			'arbs' => 20,
			'arbsk' => 'Aa',
			'arh' => '红色的丝带',
			'arhk' => 'DH',
			'arhe' => 800,
			'arhs' => 15,
			'arhsk' => 'B',
			'arf' => '黑色布鞋',
			'arfk' => 'DF',
			'arfe' => 800,
			'arfs' => 21,
			'ara' => '红色的丝带',
			'arak' => 'DA',
			'arae' => 800,
			'aras' => 15,
			'arask' => 'b',
			'art' => '红黑色的耳塞',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'W',
			'sub' => array
			(
				0 => array
				(
					'name' => '■',
					'icon' => 83,
					'wep' => '红色的丝带',
					'wepk' => 'WP',
					'wepe' => 800,
					'weps' => 20,
					'wepsk' => 'uy',
					'itm1' => '十字发卡',
					'itmk1' => 'Y',
					'itme1' => 1,
					'itms1' => 1,
					'description' => '拟似意识 ■ (通称篝)。如果仓促上阵，<span class="yellow b">不仅难以击倒她，而且很容易屈死于她之手！</span>',
				),
			),
		),//END OF TYPE 4
		
		7 => array
		(
			'mode' => 1,
			'num' => 3,
			'pass' => 'bra',
			'club' => 9,
			'bid' => 0,
			'inf' => '',
			'rage' => 100,
			'pose'=> 1,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'pls' => 99,
			'mhp' => 2550,
			'msp' => 400,
			'att' => 250,
			'def' => 750,
			'lvl' => 60,
			'skill' => 500,
			'money' => 24000,
			'arb' => '【执行官装甲-改】',
			'arbk' => 'DB',
			'arbe' => 700,
			'arbs' => 120,
			'arbsk' => 'Aa',
			'arh' => '【执行官头盔-改】',
			'arhk' => 'DH',
			'arhe' => 500,
			'arhs' => 120,
			'arhsk' => '',
			'arf' => '【执行官战靴-改】',
			'arfk' => 'DF',
			'arfe' => 480,
			'arfs' => 120,
			'arfsk' => '',
			'ara' => '【执行官护手-改】',
			'arak' => 'DA',
			'arae' => 480,
			'aras' => 120,
			'arask' => 'c',
			'art' => '【HP制御系统】',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'H',
	//		'itm5' => '好人卡',
	//		'itmk5' => 'Y',
	//		'itme5' => 1,
	//		'itms5' => 240,
			'sub' => array
			(
				0 => array
				(
					'name' => '电击使 御坂 美琴',
					'icon' => 41,
					'gd' => 'f',
					'wep' => '【科学的超电磁炮-改】',
					'wepk' => 'WG',
					'wepe' => 770,
					'weps' => 999,
					'wepsk' => 'ed',
					'itm1' => '社员专用的ID卡',
					'itmk1' => 'Z',
					'itme1' => 1,
					'itms1' => 1,
				),
				1 => array
				(
					'name' => '班主任 坂持 金发',
					'icon' => 42,
					'gd' => 'm',
					'wep' => '【水素粒子水铁炮-改】',
					'wepk' => 'WG',
					'wepe' => 770,
					'weps' => 999,
					'wepsk' => 'id',
					'itm1' => '社员专用的ID卡',
					'itmk1' => 'Z',
					'itme1' => 1,
					'itms1' => 1,
				),
				2 => array
				(
					'name' => '花之领主 风见 幽香',
					'icon' => 43,
					'gd' => 'f',
					'wep' => '魔炮【元祖二重魔炮】',
					'wepk' => 'WF',
					'wepe' => 770,
					'weps' => 999,
					'wepsk' => 'pd',
					'itm1' => '社员专用的ID卡',
					'itmk1' => 'Z',
					'itme1' => 1,
					'itms1' => 1,
				),
			),
		),//END OF TYPE 7
		
		12 => array
		(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 99,
			'bid' => 0,
			'inf' => '',
			'skills' => array('401'=>'5'),
			'state' => 1,
			'rage' => 10,
			'pose'=> 4,
			'tactic' => 4,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'f',
			'pls' => 99,
			'mhp' => 1800,
			'msp' => 400,
			'att' => 150,
			'def' => 260,
			'lvl' => 18,
			'skill' => 30,
			'money' => 1,
			'arb' => '黑色哥特装',
			'arbk' => 'DB',
			'arbe' => 25,
			'arbs' => 20,
			'arh' => '不明饰物',
			'arhk' => 'DH',
			'arhe' => 12,
			'arhs' => 15,
			'arf' => '黑色布鞋',
			'arfk' => 'DF',
			'arfe' => 18,
			'arfs' => 21,
			'ara' => '黑铁镣铐',
			'arak' => 'DA',
			'arae' => 5,
			'aras' => 15,
			'art' => '镣铐的碎片',
			'artk' => 'Y',
			'arte' => 1,
			'arts' => 1,
			'sub' => array
			(
				0 => array
				(
					'name' => 'Dark Force幼体',
					'icon' => 81,
					'wep' => 'RV『Black Riper』',
					'wepk' => 'WG',
					'wepe' => 80,
					'weps' => 125,
					'wepsk' => 'c',
				),
			),
		),//END OF TYPE 12
		
		13 => array
		(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 99,
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 5,
			'pose'=> 0,
			'tactic' => 0,
			'killnum' => 0,
			'teamID' => '循环',
			'teampsss' => 'circle',
			'gd' => 'f',
			'pls' => 99,
			'mhp' => 600,
			'msp' => 400,
			'att' => 150,
			'def' => 100,
			'lvl' => 10,
			'skill' => 50,
			'money' => 500,
			'arb' => '旧式布拉吉',
			'arbk' => 'DB',
			'arbe' => 75,
			'arbs' => 20,
			'arbsk' => '',
			'arh' => '蝙蝠羽翼帽子',
			'arhk' => 'DH',
			'arhe' => 75,
			'arhs' => 20,
			'arf' => '女式皮鞋',
			'arfk' => 'DF',
			'arfe' => 75,
			'arfs' => 20,
			'ara' => '粉色披风',
			'arak' => 'DA',
			'arae' => 50,
			'aras' => 25,
			'art' => '飞行之愿',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'H',
			'sub' => array
			(
				0 => array
				(
					'name' => '库特',
					'icon' => 8,
					'wep' => '光束镰刀',
					'wepk' => 'WK',
					'wepe' => 100,
					'weps' => 36,
					'wepsk' => 'ec',
				),
			),
		), //END OF TYPE 13
		
		42 => array
		(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 17,
			'bid' => 0,
			'inf' => '',
			'rage' => 0,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teamPass' => '',
			'gd' => 'f',
			'pls' => 34,
			'mhp' => 37000000,
			'msp' => 8000,
			'att' => 115,
			'def' => 115,
			'lvl' => 115,
			'skill' => 666,
			'skills' => array('21'=>'0','81'=>'0', '432'=>'0', '461'=>'1', '508'=>'0', '509'=>'0'),
			'money' => 115,
			'arb' => '直播长睡袍「Kipli」',
			'arbk' => 'DB',
			'arbe' => 1690000,
			'arbs' => 900,
			'arbsk' => 'Bh',
			'arh' => '橘色虎纹猫「15」',
			'arhk' => 'DH',
			'arhe' => 1440000,
			'arhs' => 900,
			'arhsk' => 'Lny',
			'ara' => '危险塑料袋「Nata」',
			'arak' => 'DA',
			'arae' => 1440000,
			'aras' => 900,
			'arask' => 'Ha',
			'arf' => '邋遢棉毛袜「Aich」',
			'arfk' => 'DF',
			'arfe' => 1440000,
			'arfs' => 900,
			'arfsk' => 'AM',
			'art' => 'V.H.虚拟娱乐主义',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'Vtb',
			'sub' => array
			(
				0 => array
				(
					'name' => '一一五',
					'icon' => 'avatar_rek/115_s.png',
					'wep' => '黄金·沙漠之鹰',
					'wepk' => 'WG',
					'wepe' => 20000,
					'weps' => 9999,
					'wepsk' => 'wNy',
					'itm1' => '开心的刀',
					'itmk1' => 'WK',
					'itme1' => 32767,
					'itms1' => 9999,
					'itmsk1' => 'crfN',
					'itm2' => '发条式突击步枪 AR-47',
					'itmk2' => 'WG',
					'itme2' => 18000,
					'itms2' => 9999,
					'itmsk2' => 'rnN',
					'itm3' => '神圣手榴弹',
					'itmk3' => 'WC',
					'itme3' => 32000,
					'itms3' => 9999,
					'itmsk3' => 'dkN',
					'description' => '断罪女神 一一五，身上的装备其实是权限套装<s style="color:#333">外挂</s>。其极端突出的攻防让她本身的操作变得无关紧要了。',
				),
			),
		),//END OF TYPE 42
		
		46 => array
		(
			'mode' => 2,
			'num' => 1,
			'pass' => 'bra',
			'club' => 17,
			'bid' => 0,
			'inf' => '',
			'rage' => 15,
			'pose'=> 2,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teampass' => '',
			'pls' => 99,
			'mhp' => 4400,
			'msp' => 1000,
			'att' => 300,
			'def' => 500,
			'lvl' => 40,
			'skill' => 333,
			'money' => 20,
			'arb' => '全息实体战装',
			'arbk' => 'DB',
			'arbe' => 1200,
			'arbs' => 30,
			'arbsk' => 'A',
			'arh' => '全息实体战盔',
			'arhk' => 'DH',
			'arhe' => 1200,
			'arhs' => 30,
			'arhsk' => 'a',
			'ara' => '全息实体战盾',
			'arak' => 'DA',
			'arae' => 1200,
			'aras' => 30,
			'arask' => 'R',
			'arf' => '全息实体战靴',
			'arfk' => 'DF',
			'arfe' => 1200,
			'arfs' => 30,
			'arfsk' => 'M',
			'art' => '全息实体的自律回路',
			'artk' => 'A',
			'arte' => 1200,
			'arts' => 30,
			'artsk' => 'cH',
			'sub' => array
			(
				0 => array
				 (
					'name' => '熵魔法传人 Howling',
					'icon' => 'avatar_kh/howling.jpg',
					'gd' => 'f',
					'mss' => 50,
					'skills' => array('404'=>'3','461'=>'1','486'=>'2'),
					'wep' => '烈爪拳 Huitzil',
					'wepk' => 'WP',
					'wepe' => 360,
					'weps' => 600,
					'wepsk' => 'ufr',
					'arb' => '蓬松运动连衣裙',
					'arh' => '异域风情的围巾',
					'ara' => '附魔之神爪 Ketsal',
					'arask' => 'NR',
					'arf' => '前端开口的长筒靴',
					'itm1' => '★长着兽耳的卡牌包★',
					'itmk1' => 'VO4',
					'itme1' => 1,
					'itms1' => 1,
					'itmsk1' => '201',
					'description' => '全息实体 熵魔法传人 Howling，同名全息幻象被全部击杀时才会登场的完全体。残血时物理伤害会增加600点，特色是残血时概率复活',
				),
				1 => array
				(
					'name' => '幻影斗将神 S.A.S',
					'icon' => 'avatar_kh/SAS.jpg',
					'gd' => 'f',
					'mss' => 50,
					'skills' => array('404'=>'3','461'=>'1','485'=>'2'),
					'wep' => '断天镰·碎星',
					'wepk' => 'WK',
					'wepe' => 360,
					'weps' => 600,
					'wepsk' => 'rnc',
					'arb' => '圣战士之甲',
					'arh' => '圣战士之盔',
					'ara' => '圣战士之盾',
					'arf' => '圣战士之靴',
					'itm1' => '★锋利的卡牌包★',
					'itmk1' => 'VO4',
					'itme1' => 1,
					'itms1' => 1,
					'itmsk1' => '200',
					'description' => '全息实体 幻影斗将神 S.A.S，同名全息幻象被全部击杀时才会登场的完全体。残血时物理伤害会增加600点，特色是对杀人数越多的对手造成的伤害越大',
				),
				2 => array
				(
					'name' => '银白愿天使 Annabelle',
					'icon' => 'avatar_kh/annabelle.jpg',
					'gd' => 'f',
					'mss' => 50,
					'skills' => array('404'=>'3','461'=>'1','489'=>'0'),
					'wep' => '『亚兹拉尔的死亡之叶』',
					'wepk' => 'WC',
					'wepe' => 360,
					'weps' => 600,
					'wepsk' => 'Lir',
					'arb' => '密涅瓦之衣',
					'arh' => '梅塔伊恩之冠',
					'ara' => '朱庇特之巾',
					'arf' => '堕天使之羽翼',
					'arfsk' => 'Mm',
					'itm1' => '★羽翼卡牌包★',
					'itmk1' => 'VO4',
					'itme1' => 1,
					'itms1' => 1,
					'itmsk1' => '203',
					'description' => '全息实体 银白愿天使 Annabelle，同名全息幻象被全部击杀时才会登场的完全体。残血时物理伤害会增加600点，特色是会将所受的异常状态反弹给对手。',
				),
				3 => array
				(
					'name' => '通灵冒险家 星海',
					'icon' => 'avatar_kh/xinghai.jpg',
					'gd' => 'f',
					'mss' => 50,
					'skills' => array('404'=>'3','461'=>'1','488'=>'0'),
					'wep' => '泰瑟远距电击枪',
					'wepk' => 'WG',
					'wepe' => 360,
					'weps' => 600,
					'wepsk' => 'Ser',
					'arb' => '内插钢板的西装',
					'arh' => '水晶灵视眼镜',
					'ara' => '内藏机关的手套',
					'arf' => '耐磨的灰色长裤',
					'arfs' => 200,
					'itm1' => '★套了好几层的卡牌包★',
					'itmk1' => 'VO4',
					'itme1' => 1,
					'itms1' => 1,
					'itmsk1' => '202',
					'description' => '全息实体 通灵冒险家 星海，同名全息幻象被全部击杀时才会登场的完全体。残血时物理伤害会增加600点，特色是HP低于一半后会回复受到攻击一半的生命值',
				),
				4 => array
				(
					'name' => '麻烦妖精 Sophia',
					'icon' => 'avatar_kh/sophia.jpg',
					'gd' => 'f',
					'mss' => 50,
					'skills' => array('404'=>'3','461'=>'1','491'=>'0'),
					'wep' => '空想波动 ~ 共鸣冲击',
					'wepk' => 'WD',
					'wepe' => 360,
					'weps' => 600,
					'wepsk' => 'rwd',
					'arb' => '空想模样的裙子',
					'arh' => '空想模样的头饰',
					'ara' => '空想模样的手套',
					'arf' => '空想模样的靴子',
					'itm1' => '★蠢萌的卡牌包★',
					'itmk1' => 'VO4',
					'itme1' => 1,
					'itms1' => 1,
					'itmsk1' => '204',
					'description' => '全息实体 麻烦妖精 Sophia，同名全息幻象被全部击杀时才会登场的完全体。残血时物理伤害会增加600点，特色是随机强化武器效果。',
				),
			),
		),//END OF TYPE 46
	);//END OF $anpcinfo
}

?>