<?php

$language = array
	(
	'title' => 'ACFUN 大 逃 杀',
	
	'index' => '首页',
	'fullwin' => '全屏模式',
	'backindex' => '返回首页',
	
	'register' => '账号注册',
	'user' => '帐号资料',
	'messages' => '站内邮件',
	'game' => '进入游戏',
	'map' => '战场地图',
	'news' => '进行状况',
	'alive' => '当前幸存',
	'winner' => '历史优胜',
	'rank' => '玩家排行',
	'help' => '游戏帮助',
	'logistics' => '后勤商店',
	'homepage' => '官方网站',
	'admin' => '游戏管理',
	'report' => '官方讨论区',
	
	'now' => '当前时刻',
	'gameversion' => '游戏版本',
	'gameinfo' => '游戏情报',
	'adminmsg' => '站长留言',
	'systemmsg' => '系统状况',
	'username' => '账号',
	'password' => '密码',
	'welcome' => '欢迎你，{$cuser}！',
	'login' => '登录',
	'numinfo' => '第 $gamenum 回游戏 ',
	'gamedate' => '{$month}月{$day}日 星期{$week["$wday"]} {$hour}:{$min}',
	'back' => '返回',
	'submit' => '提交',
	'reset' => '重设',
	
	'basicdata' => '账户基本资料',
	'advanceddata' => '账户个性化资料',
	'usersettings' => '游戏设置',
	'opass' => '原密码',
	'npass' => '新密码',
	'rnpass' => '重复新密码',
	'editpass' => '修改密码点此（未完成）',
	'username_comment' => '最长15个字符，半角符号除外',
	'password_comment' => '最长24个字符',
	'r_password_comment' => '密码与重复密码需相同',
	'motto' => '口头禅',
	'killmsg' => '杀人宣言',
	'lastword' => '遗言',
	'o_password_comment' => '修改密码需输入正确的原密码',
	'n_password_comment' => '最长24个字符，留空为不修改',
	
	'motto_comment' => '写下彰显个性的台词，30个字以内。',
	'killmsg_comment' => '写下杀死对手的留言，30个字以内',
	'lastword_comment' => '写下不幸被害时的台词，30个字以内',
	'credits' => '积分',
	'lastgame' => '最后游戏',
	'validgames' => '游戏场数',
	'wingames' => '获胜场数',
	'winrate' => '胜率',
	
	'valid' => '入场手续',
	'validover' => '入场表格填写完成',
	'enternotice' => '进入会场',
	'enterbattlefield' => '进入大逃杀战场',
	'gamestart' => '游戏开始',
	'enter' => '进入游戏',
	'quit' => '账号退出',
	'errormsg' => '出现错误',
	
	'tutorial' => '游戏教程',
	'enterturorial' => '观看游戏教程',
	'nexttutorial' => '下一篇教程',
	
	'name' => '姓名',
	'gender' => '性别',
	'icon' => '头像',
	'sNo' => '学号',
	'level' => '等级',
	'club' => '内定称号',
	'hp' => '生命',
	'sp' => '体力',
	'att' => '攻击力',
	'def' => '防御力',
	'combo' => '连斗',
	'duel' => '死斗',
	'exp' => '经验值',
	'weather' => '天气',
	'status' => '状态',
	'team' => '队伍',
	'inf' => '受伤部位',
	'pose' => '基础姿态',
	'tactic' => '应战策略',
	'kind1' => '种类',
	'rage' => '怒气',
	'killnum' => '击杀数',
	'pckillnum' => '击杀玩家数',
	'npckillnum' => '击杀NPC数',
	'money' => '金钱',
	'equip' => '装备',
	'pack' => '包裹',
	'startpack' => '随机道具',
	'skill' => '熟',
	'command' => '指令',
	'wep' => '武器',
	'arb' => '防具',
	'effect' => '攻击',
	'cmd_choice' => '你想要做什么？',
	'chat' => '消息',
	'moneyunit' => '元',
	'wp' => '殴',
	'wk' => '斩',
	'wg' => '射',
	'wc' => '投',
	'wd' => '爆',
	'wf' => '灵',
	'ss' => '歌魂',
	'karma' => '罪业',
	'newsnotice' => '<span class="evergreen b">“各位仍在努力奋战，咱很欣慰。<br />以下是到现在为止的游戏状况。<br />请各位再接再厉。”</span>',
	'useitem' => '>>使用',
	'end' => '游戏结束！',
	'send' => '发送',
	'refresh' => '刷新',
	'maptitle' => '虚拟世界地图',
	);


?>