<?php

namespace aprilfool2018
{
	$snpcinfo = array
	( 
		41 => array
			(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 17,
			'bid' => 0,
			'inf' => '',
			'rage' => 0,
			'pose'=> 1,
			'tactic' => 3,
			'killnum' => 0,
			'teamID' => '',
			'teamPass' => '',
			'gd' => 'f',
			'pls' => 99,
			'mhp' => 37000000,
			'msp' => 8000,
			'att' => 115,
			'def' => 115,
			'lvl' => 15,
			'skill' => 115,
			'skills' => array('81'=>'0', '404'=>'0', '432'=>'0', '461'=>'0', '506'=>'0', '507'=>'0'),
			'money' => 115,
			'arb' => '直播长睡袍「Kipli」',
			'arbk' => 'DB',
			'arbe' => 16900000,
			'arbs' => 900,
			'arbsk' => 'h',
			'arh' => '橘色虎纹猫「15」',
			'arhk' => 'DH',
			'arhe' => 14400000,
			'arhs' => 900,
			'arhsk' => 'b',
			'ara' => '危险塑料袋「Nata」',
			'arak' => 'DA',
			'arae' => 14400000,
			'aras' => 900,
			'arask' => 'HL',
			'arf' => '邋遢棉毛袜「Aich」',
			'arfk' => 'DF',
			'arfe' => 14400000,
			'arfs' => 900,
			'arfsk' => 'Aa',
			'art' => 'V.H.虚拟娱乐主义',
			'artk' => 'A',
			'arte' => 1,
			'arts' => 1,
			'artsk' => 'Vtb',
			'sub' => array
			(
				0 => array
				(
				'name' => '一一五',
				'icon' => 'avatar_rek/115.png',
				'wep' => '黄金·沙漠之鹰',
				'wepk' => 'WG',
				'wepe' => 200,
				'weps' => 9999,
				'wepsk' => 'wN',
				'itm1' => '「真刀」',
				'itmk1' => 'WK',
				'itme1' => 99,
				'itms1' => 9999,
				'itmsk1' => 'cfN',
				'itm2' => '突击步枪 AKM',
				'itmk2' => 'WG',
				'itme2' => 180,
				'itms2' => 9999,
				'itmsk2' => 'rN',
				'itm3' => '高爆手雷',
				'itmk3' => 'WC',
				'itme3' => 270,
				'itms3' => 9999,
				'itmsk3' => 'dN',
				'itm5' => '奇怪的按钮',
				'itmk5' => 'Y',
				'itme5' => 1,
				'itms5' => 1,
				),
			),
		),
	);
}

?>