<?php

namespace tutorial
{
	$npcinit = array
		(
			'name' => '',	'pass' => 'bra', 'gd' => 'm',	'icon' => 0,	'club' => 0,	
			'mhp' => 0,	'msp' => 0,	'att' => 0,	'def' => 0,	'pls' => 0,	'lvl' => 0,
			'money' => 0,	'inf' => '',	'rage' => 0,	'pose' => 0,	'tactic' => 0,	
			'killnum' => 0,	'state' => 1,	'teamID' => '',	'teamPass' => '','bid' => 0,
			'wep' => '',	'wepk' => '',	'wepe' => 0,	'weps' => 0,	'wepsk' => '',
			'arb' => '',	'arbk' => '',	'arbe' => 0,	'arbs' => 0,	'arbsk' => '',
			'arh' => '',	'arhk' => '',	'arhe' => 0,	'arhs' => 0,	'arhsk' => '',
			'arf' => '',	'arfk' => '',	'arfe' => 0,	'arfs' => 0,	'arfsk' => '',
			'ara' => '',	'arak' => '',	'arae' => 0,	'aras' => 0,	'arask' => '',
			'art' => '',	'artk' => '',	'arte' => 0,	'arts' => 0,	'artsk' => '',
			'itm0' => '',	'itmk0' => '',	'itme0' => 0,	'itms0' => 0,	'itmsk0' => '',
			'itm1' => '',	'itmk1' => '',	'itme1' => 0,	'itms1' => 0,	'itmsk1' => '',
			'itm2' => '',	'itmk2' => '',	'itme2' => 0,	'itms2' => 0,	'itmsk2' => '',
			'itm3' => '',	'itmk3' => '',	'itme3' => 0,	'itms3' => 0,	'itmsk3' => '',
			'itm4' => '',	'itmk4' => '',	'itme4' => 0,	'itms4' => 0,	'itmsk4' => '',
			'itm5' => '',	'itmk5' => '',	'itme5' => 0,	'itms5' => 0,	'itmsk5' => '',
			'itm6' => '',	'itmk6' => '',	'itme6' => 0,	'itms6' => 0,	'itmsk6' => '',
		);
	$tnpcinfo = array
		( 
		9 => array
			(
			'mode' => 2,
			'num' => 1,
			'pass' => 'bra',
			'club' => 0,
			'bid' => 0,
			'inf' => '',
			'rage' => 0,
			'pose'=> 0,
			'tactic' => 0,
			'killnum' => 0,
			'teamID' => '',
			'teamPass' => '',
			'gd' => 'm',
			'pls' => 99,
			'mhp' => 400,
			'msp' => 100,
			'att' => 200,
			'def' => 200,
			'lvl' => 15,
			'skill' => 100,
			'money' => 1200,
			'arb' => '红杀战甲',
			'arbk' => 'DB',
			'arbe' => 80,
			'arbs' => 60,
			'arbsk' => '',
			'arh' => '红杀战盔',
			'arhk' => 'DH',
			'arhe' => 60,
			'arhs' => 30,			
			'arf' => '红杀战靴',
			'arfk' => 'DF',
			'arfe' => 75,
			'arfs' => 30,
			'arfsk' => '',
			'ara' => '红杀辅助瞄准系统S.A.T.S.',
			'arak' => 'DA',
			'arae' => 120,
			'aras' => 30,
			'arask' => 'c',
			
			'sub' => array
			(
			0 => array
				(
				'name' => '弗勒尔',
				'icon' => 0,
				'wep' => '【红杀之牙】',
				'wepk' => 'WK',
				'wepe' => 120,
				'weps' => 100,
				'arask' => 'nu',
				),
			),
		),
		91 => array
			(
			'mode' => 1,
			'num' => 1,
			'pass' => 'bra',
			'club' => 9,
			'bid' => 0,
			'inf' => '',
			'state' => 1,
			'rage' => 15,
			'pose'=> 0,
			'tactic' => 0,
			'killnum' => 0,
			'teamID' => '',
			'teampsss' => '',
			'gd' => 'r',
			'pls' => 99,
			'mhp' => 100,
			'msp' => 100,
			'att' => 120,
			'def' => 80,
			'lvl' => 1,
			'skill' => 50,
			'money' => 400,
			'arb' => '便服',
			'arbk' => 'DB',
			'arbe' => 10,
			'arbs' => 20,
			'arbsk' => '',
			'arh' => '鸭舌帽',
			'arhk' => 'DH',
			'arhe' => 10,
			'arhs' => 15,
			'arf' => '布鞋',
			'arfk' => 'DF',
			'arfe' => 10,
			'arfs' => 10,
			'ara' => '塑料盾',
			'arak' => 'DA',
			'arae' => 10,
			'aras' => 15,
			'arask' => '',
			'sub' => array
			(
				0 => array
				(
				'name' => '自律人偶',
				'icon' => 9,
				'wep' => '镇暴失能针',
				'wepk' => 'WK',
				'wepe' => 50,
				'weps' => 20,
				'wepsk' => 'p',
				),
			),
		),
	);
}

?>